uistring:
    title: Green Meteor
    description: Bring new modules & themes to HumHub projects
    copyright: 2017 Green Meteor, Inc.
    github_button_location_page_bottom: true

favicon: ico/16x16.ico

theme: jekyll-theme-minimal
